// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anomalousventures/tracks/internal/cli/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProjectDetector creates a new instance of MockProjectDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectDetector {
	mock := &MockProjectDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectDetector is an autogenerated mock type for the ProjectDetector type
type MockProjectDetector struct {
	mock.Mock
}

type MockProjectDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectDetector) EXPECT() *MockProjectDetector_Expecter {
	return &MockProjectDetector_Expecter{mock: &_m.Mock}
}

// Detect provides a mock function for the type MockProjectDetector
func (_mock *MockProjectDetector) Detect(ctx context.Context, startDir string) (*interfaces.TracksProject, string, error) {
	ret := _mock.Called(ctx, startDir)

	if len(ret) == 0 {
		panic("no return value specified for Detect")
	}

	var r0 *interfaces.TracksProject
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*interfaces.TracksProject, string, error)); ok {
		return returnFunc(ctx, startDir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *interfaces.TracksProject); ok {
		r0 = returnFunc(ctx, startDir)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*interfaces.TracksProject)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, startDir)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, startDir)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockProjectDetector_Detect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detect'
type MockProjectDetector_Detect_Call struct {
	*mock.Call
}

// Detect is a helper method to define mock.On call
//   - ctx context.Context
//   - startDir string
func (_e *MockProjectDetector_Expecter) Detect(ctx interface{}, startDir interface{}) *MockProjectDetector_Detect_Call {
	return &MockProjectDetector_Detect_Call{Call: _e.mock.On("Detect", ctx, startDir)}
}

func (_c *MockProjectDetector_Detect_Call) Run(run func(ctx context.Context, startDir string)) *MockProjectDetector_Detect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectDetector_Detect_Call) Return(tracksProject *interfaces.TracksProject, s string, err error) *MockProjectDetector_Detect_Call {
	_c.Call.Return(tracksProject, s, err)
	return _c
}

func (_c *MockProjectDetector_Detect_Call) RunAndReturn(run func(ctx context.Context, startDir string) (*interfaces.TracksProject, string, error)) *MockProjectDetector_Detect_Call {
	_c.Call.Return(run)
	return _c
}

// HasTemplUIConfig provides a mock function for the type MockProjectDetector
func (_mock *MockProjectDetector) HasTemplUIConfig(ctx context.Context, projectDir string) bool {
	ret := _mock.Called(ctx, projectDir)

	if len(ret) == 0 {
		panic("no return value specified for HasTemplUIConfig")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, projectDir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProjectDetector_HasTemplUIConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasTemplUIConfig'
type MockProjectDetector_HasTemplUIConfig_Call struct {
	*mock.Call
}

// HasTemplUIConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
func (_e *MockProjectDetector_Expecter) HasTemplUIConfig(ctx interface{}, projectDir interface{}) *MockProjectDetector_HasTemplUIConfig_Call {
	return &MockProjectDetector_HasTemplUIConfig_Call{Call: _e.mock.On("HasTemplUIConfig", ctx, projectDir)}
}

func (_c *MockProjectDetector_HasTemplUIConfig_Call) Run(run func(ctx context.Context, projectDir string)) *MockProjectDetector_HasTemplUIConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProjectDetector_HasTemplUIConfig_Call) Return(b bool) *MockProjectDetector_HasTemplUIConfig_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProjectDetector_HasTemplUIConfig_Call) RunAndReturn(run func(ctx context.Context, projectDir string) bool) *MockProjectDetector_HasTemplUIConfig_Call {
	_c.Call.Return(run)
	return _c
}
