// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"database/sql"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDatabaseManager creates a new instance of MockDatabaseManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatabaseManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatabaseManager {
	mock := &MockDatabaseManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatabaseManager is an autogenerated mock type for the DatabaseManager type
type MockDatabaseManager struct {
	mock.Mock
}

type MockDatabaseManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatabaseManager) EXPECT() *MockDatabaseManager_Expecter {
	return &MockDatabaseManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatabaseManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatabaseManager_Expecter) Close() *MockDatabaseManager_Close_Call {
	return &MockDatabaseManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatabaseManager_Close_Call) Run(run func()) *MockDatabaseManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseManager_Close_Call) Return(err error) *MockDatabaseManager_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_Close_Call) RunAndReturn(run func() error) *MockDatabaseManager_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) Connect(ctx context.Context) (*sql.DB, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 *sql.DB
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*sql.DB, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *sql.DB); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatabaseManager_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockDatabaseManager_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDatabaseManager_Expecter) Connect(ctx interface{}) *MockDatabaseManager_Connect_Call {
	return &MockDatabaseManager_Connect_Call{Call: _e.mock.On("Connect", ctx)}
}

func (_c *MockDatabaseManager_Connect_Call) Run(run func(ctx context.Context)) *MockDatabaseManager_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_Connect_Call) Return(dB *sql.DB, err error) *MockDatabaseManager_Connect_Call {
	_c.Call.Return(dB, err)
	return _c
}

func (_c *MockDatabaseManager_Connect_Call) RunAndReturn(run func(ctx context.Context) (*sql.DB, error)) *MockDatabaseManager_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatabaseURL provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) GetDatabaseURL() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatabaseURL")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDatabaseManager_GetDatabaseURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatabaseURL'
type MockDatabaseManager_GetDatabaseURL_Call struct {
	*mock.Call
}

// GetDatabaseURL is a helper method to define mock.On call
func (_e *MockDatabaseManager_Expecter) GetDatabaseURL() *MockDatabaseManager_GetDatabaseURL_Call {
	return &MockDatabaseManager_GetDatabaseURL_Call{Call: _e.mock.On("GetDatabaseURL")}
}

func (_c *MockDatabaseManager_GetDatabaseURL_Call) Run(run func()) *MockDatabaseManager_GetDatabaseURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseManager_GetDatabaseURL_Call) Return(s string) *MockDatabaseManager_GetDatabaseURL_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDatabaseManager_GetDatabaseURL_Call) RunAndReturn(run func() string) *MockDatabaseManager_GetDatabaseURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetDriver provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) GetDriver() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDriver")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDatabaseManager_GetDriver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDriver'
type MockDatabaseManager_GetDriver_Call struct {
	*mock.Call
}

// GetDriver is a helper method to define mock.On call
func (_e *MockDatabaseManager_Expecter) GetDriver() *MockDatabaseManager_GetDriver_Call {
	return &MockDatabaseManager_GetDriver_Call{Call: _e.mock.On("GetDriver")}
}

func (_c *MockDatabaseManager_GetDriver_Call) Run(run func()) *MockDatabaseManager_GetDriver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatabaseManager_GetDriver_Call) Return(s string) *MockDatabaseManager_GetDriver_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDatabaseManager_GetDriver_Call) RunAndReturn(run func() string) *MockDatabaseManager_GetDriver_Call {
	_c.Call.Return(run)
	return _c
}

// LoadEnv provides a mock function for the type MockDatabaseManager
func (_mock *MockDatabaseManager) LoadEnv(ctx context.Context, projectDir string) error {
	ret := _mock.Called(ctx, projectDir)

	if len(ret) == 0 {
		panic("no return value specified for LoadEnv")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, projectDir)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatabaseManager_LoadEnv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadEnv'
type MockDatabaseManager_LoadEnv_Call struct {
	*mock.Call
}

// LoadEnv is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
func (_e *MockDatabaseManager_Expecter) LoadEnv(ctx interface{}, projectDir interface{}) *MockDatabaseManager_LoadEnv_Call {
	return &MockDatabaseManager_LoadEnv_Call{Call: _e.mock.On("LoadEnv", ctx, projectDir)}
}

func (_c *MockDatabaseManager_LoadEnv_Call) Run(run func(ctx context.Context, projectDir string)) *MockDatabaseManager_LoadEnv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatabaseManager_LoadEnv_Call) Return(err error) *MockDatabaseManager_LoadEnv_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatabaseManager_LoadEnv_Call) RunAndReturn(run func(ctx context.Context, projectDir string) error) *MockDatabaseManager_LoadEnv_Call {
	_c.Call.Return(run)
	return _c
}
