// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/anomalousventures/tracks/internal/cli/interfaces"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUIExecutor creates a new instance of MockUIExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUIExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUIExecutor {
	mock := &MockUIExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUIExecutor is an autogenerated mock type for the UIExecutor type
type MockUIExecutor struct {
	mock.Mock
}

type MockUIExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUIExecutor) EXPECT() *MockUIExecutor_Expecter {
	return &MockUIExecutor_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockUIExecutor
func (_mock *MockUIExecutor) Add(ctx context.Context, projectDir string, ref string, components []string, force bool) error {
	ret := _mock.Called(ctx, projectDir, ref, components, force)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []string, bool) error); ok {
		r0 = returnFunc(ctx, projectDir, ref, components, force)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUIExecutor_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockUIExecutor_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
//   - ref string
//   - components []string
//   - force bool
func (_e *MockUIExecutor_Expecter) Add(ctx interface{}, projectDir interface{}, ref interface{}, components interface{}, force interface{}) *MockUIExecutor_Add_Call {
	return &MockUIExecutor_Add_Call{Call: _e.mock.On("Add", ctx, projectDir, ref, components, force)}
}

func (_c *MockUIExecutor_Add_Call) Run(run func(ctx context.Context, projectDir string, ref string, components []string, force bool)) *MockUIExecutor_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockUIExecutor_Add_Call) Return(err error) *MockUIExecutor_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUIExecutor_Add_Call) RunAndReturn(run func(ctx context.Context, projectDir string, ref string, components []string, force bool) error) *MockUIExecutor_Add_Call {
	_c.Call.Return(run)
	return _c
}

// IsAvailable provides a mock function for the type MockUIExecutor
func (_mock *MockUIExecutor) IsAvailable(ctx context.Context, projectDir string) bool {
	ret := _mock.Called(ctx, projectDir)

	if len(ret) == 0 {
		panic("no return value specified for IsAvailable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, projectDir)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockUIExecutor_IsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsAvailable'
type MockUIExecutor_IsAvailable_Call struct {
	*mock.Call
}

// IsAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
func (_e *MockUIExecutor_Expecter) IsAvailable(ctx interface{}, projectDir interface{}) *MockUIExecutor_IsAvailable_Call {
	return &MockUIExecutor_IsAvailable_Call{Call: _e.mock.On("IsAvailable", ctx, projectDir)}
}

func (_c *MockUIExecutor_IsAvailable_Call) Run(run func(ctx context.Context, projectDir string)) *MockUIExecutor_IsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUIExecutor_IsAvailable_Call) Return(b bool) *MockUIExecutor_IsAvailable_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockUIExecutor_IsAvailable_Call) RunAndReturn(run func(ctx context.Context, projectDir string) bool) *MockUIExecutor_IsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockUIExecutor
func (_mock *MockUIExecutor) List(ctx context.Context, projectDir string, ref string) ([]interfaces.UIComponent, error) {
	ret := _mock.Called(ctx, projectDir, ref)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []interfaces.UIComponent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]interfaces.UIComponent, error)); ok {
		return returnFunc(ctx, projectDir, ref)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []interfaces.UIComponent); ok {
		r0 = returnFunc(ctx, projectDir, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interfaces.UIComponent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectDir, ref)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUIExecutor_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockUIExecutor_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
//   - ref string
func (_e *MockUIExecutor_Expecter) List(ctx interface{}, projectDir interface{}, ref interface{}) *MockUIExecutor_List_Call {
	return &MockUIExecutor_List_Call{Call: _e.mock.On("List", ctx, projectDir, ref)}
}

func (_c *MockUIExecutor_List_Call) Run(run func(ctx context.Context, projectDir string, ref string)) *MockUIExecutor_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUIExecutor_List_Call) Return(uIComponents []interfaces.UIComponent, err error) *MockUIExecutor_List_Call {
	_c.Call.Return(uIComponents, err)
	return _c
}

func (_c *MockUIExecutor_List_Call) RunAndReturn(run func(ctx context.Context, projectDir string, ref string) ([]interfaces.UIComponent, error)) *MockUIExecutor_List_Call {
	_c.Call.Return(run)
	return _c
}

// Upgrade provides a mock function for the type MockUIExecutor
func (_mock *MockUIExecutor) Upgrade(ctx context.Context, projectDir string, ref string) error {
	ret := _mock.Called(ctx, projectDir, ref)

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, projectDir, ref)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUIExecutor_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type MockUIExecutor_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
//   - ref string
func (_e *MockUIExecutor_Expecter) Upgrade(ctx interface{}, projectDir interface{}, ref interface{}) *MockUIExecutor_Upgrade_Call {
	return &MockUIExecutor_Upgrade_Call{Call: _e.mock.On("Upgrade", ctx, projectDir, ref)}
}

func (_c *MockUIExecutor_Upgrade_Call) Run(run func(ctx context.Context, projectDir string, ref string)) *MockUIExecutor_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUIExecutor_Upgrade_Call) Return(err error) *MockUIExecutor_Upgrade_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUIExecutor_Upgrade_Call) RunAndReturn(run func(ctx context.Context, projectDir string, ref string) error) *MockUIExecutor_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockUIExecutor
func (_mock *MockUIExecutor) Version(ctx context.Context, projectDir string) (string, error) {
	ret := _mock.Called(ctx, projectDir)

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, projectDir)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, projectDir)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, projectDir)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUIExecutor_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockUIExecutor_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
//   - ctx context.Context
//   - projectDir string
func (_e *MockUIExecutor_Expecter) Version(ctx interface{}, projectDir interface{}) *MockUIExecutor_Version_Call {
	return &MockUIExecutor_Version_Call{Call: _e.mock.On("Version", ctx, projectDir)}
}

func (_c *MockUIExecutor_Version_Call) Run(run func(ctx context.Context, projectDir string)) *MockUIExecutor_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUIExecutor_Version_Call) Return(s string, err error) *MockUIExecutor_Version_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUIExecutor_Version_Call) RunAndReturn(run func(ctx context.Context, projectDir string) (string, error)) *MockUIExecutor_Version_Call {
	_c.Call.Return(run)
	return _c
}
