name: Bug Report
description: Report a bug or unexpected behavior in Tracks
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible to help us investigate and fix the issue.

  - type: input
    id: tracks-version
    attributes:
      label: Tracks Version
      description: What version of Tracks are you using? Run `tracks version` to find out.
      placeholder: "v0.2.0"
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: "1.25.5"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: dropdown
    id: database
    attributes:
      label: Database Driver
      description: Which database driver are you using? (if applicable)
      options:
        - Not applicable
        - LibSQL (Turso)
        - SQLite3
        - PostgreSQL
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Execute '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Error Messages
      description: Please copy and paste any relevant log output or error messages. This will be automatically formatted as code.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
    validations:
      required: false
