name: Feature Request
description: Suggest a new feature or enhancement for Tracks
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details about your use case and proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: Describe the problem you're trying to solve or the use case you have in mind. What is the current limitation or pain point?
      placeholder: |
        I'm always frustrated when...
        I need to be able to...
        Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented. How would this feature work?
      placeholder: I'd like Tracks to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered, including workarounds you're currently using.
      placeholder: |
        I considered...
        As a workaround, I'm currently...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, examples, or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I'm willing to submit a PR to implement this feature
          required: false
