package template

import (
	"strings"
	"testing"

	"github.com/anomalousventures/tracks/internal/templates"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestReadmeTemplate(t *testing.T) {
	renderer := NewRenderer(templates.FS)

	drivers := []string{"go-libsql", "sqlite3", "postgres"}

	for _, driver := range drivers {
		t.Run(driver, func(t *testing.T) {
			data := TemplateData{
				ProjectName: "testapp",
				DBDriver:    driver,
			}

			result, err := renderer.Render("README.md.tmpl", data)
			require.NoError(t, err)
			assert.NotEmpty(t, result)
		})
	}
}

func TestReadmeProjectName(t *testing.T) {
	renderer := NewRenderer(templates.FS)

	data := TemplateData{
		ProjectName: "my-awesome-app",
		DBDriver:    "postgres",
	}

	result, err := renderer.Render("README.md.tmpl", data)
	require.NoError(t, err)

	assert.Contains(t, result, "# my-awesome-app", "should contain project name as title")
}

func TestReadmeDatabasePrerequisites(t *testing.T) {
	renderer := NewRenderer(templates.FS)

	tests := []struct {
		driver        string
		shouldContain []string
	}{
		{
			driver: "postgres",
			shouldContain: []string{
				"PostgreSQL server",
			},
		},
		{
			driver: "go-libsql",
			shouldContain: []string{
				"CGO enabled",
				"GCC (Linux) or Xcode (macOS)",
				"Turso (libSQL cloud database)",
			},
		},
		{
			driver: "sqlite3",
			shouldContain: []string{
				"CGO enabled (for sqlite3 driver)",
				"GCC (Linux) or Xcode (macOS)",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.driver, func(t *testing.T) {
			data := TemplateData{
				ProjectName: "testapp",
				DBDriver:    tt.driver,
			}

			result, err := renderer.Render("README.md.tmpl", data)
			require.NoError(t, err)

			for _, expected := range tt.shouldContain {
				assert.Contains(t, result, expected, "should contain %q for %s", expected, tt.driver)
			}
		})
	}
}

func TestReadmeContentValidation(t *testing.T) {
	renderer := NewRenderer(templates.FS)
	drivers := []string{"go-libsql", "sqlite3", "postgres"}

	testCases := []struct {
		name     string
		contains []string
	}{
		{
			name: "common_sections",
			contains: []string{
				"## Getting Started",
				"### Prerequisites",
				"### Installation",
				"### Project Structure",
				"### Development",
				"### Available Commands",
				"## Configuration",
				"## License",
			},
		},
		{
			name: "technology_stack",
			contains: []string{
				"Chi",
				"templ",
				"SQLC",
				"HTMX",
				"Mockery",
			},
		},
		{
			name: "project_structure",
			contains: []string{
				"cmd/server/",
				"internal/interfaces/",
				"internal/domain/",
				"internal/infra/http/",
				"internal/routes/",
				"db/",
				"test/mocks/",
			},
		},
		{
			name: "available_commands",
			contains: []string{
				"make help",
				"make test",
				"make build",
				"make dev",
				"make fmt",
				"make lint",
				"make generate",
				"make templ",
				"make mocks",
				"make sqlc",
			},
		},
		{
			name: "installation_steps",
			contains: []string{
				"make generate",
				"make test",
				"make dev",
			},
		},
		{
			name: "contributing_link",
			contains: []string{
				"CONTRIBUTING.md",
			},
		},
		{
			name: "configuration_section",
			contains: []string{
				".tracks.yaml",
				".env",
				".env.example",
				"cp .env.example .env",
			},
		},
		{
			name: "tracks_reference",
			contains: []string{
				"Generated by [Tracks](https://github.com/anomalousventures/tracks)",
			},
		},
		{
			name: "go_version",
			contains: []string{
				"Go 1.25 or later",
			},
		},
	}

	for _, driver := range drivers {
		t.Run(driver, func(t *testing.T) {
			data := TemplateData{
				ProjectName: "testapp",
				DBDriver:    driver,
			}

			result, err := renderer.Render("README.md.tmpl", data)
			require.NoError(t, err)

			for _, tc := range testCases {
				t.Run(tc.name, func(t *testing.T) {
					for _, expected := range tc.contains {
						assert.Contains(t, result, expected, "should contain %q", expected)
					}
				})
			}
		})
	}
}

func TestReadmeNoTODOPlaceholders(t *testing.T) {
	renderer := NewRenderer(templates.FS)

	drivers := []string{"go-libsql", "sqlite3", "postgres"}

	for _, driver := range drivers {
		t.Run(driver, func(t *testing.T) {
			data := TemplateData{
				ProjectName: "testapp",
				DBDriver:    driver,
			}

			result, err := renderer.Render("README.md.tmpl", data)
			require.NoError(t, err)

			assert.NotContains(t, result, "TODO", "should not contain TODO placeholders for %s", driver)
		})
	}
}

func TestReadmeMarkdownStructure(t *testing.T) {
	renderer := NewRenderer(templates.FS)

	data := TemplateData{
		ProjectName: "testapp",
		DBDriver:    "postgres",
	}

	result, err := renderer.Render("README.md.tmpl", data)
	require.NoError(t, err)

	lines := strings.Split(result, "\n")

	hasH1 := false
	hasH2 := false
	hasH3 := false
	hasCodeBlock := false

	for _, line := range lines {
		if strings.HasPrefix(line, "# ") {
			hasH1 = true
		}
		if strings.HasPrefix(line, "## ") {
			hasH2 = true
		}
		if strings.HasPrefix(line, "### ") {
			hasH3 = true
		}
		if strings.HasPrefix(line, "```") {
			hasCodeBlock = true
		}
	}

	assert.True(t, hasH1, "should have H1 heading")
	assert.True(t, hasH2, "should have H2 headings")
	assert.True(t, hasH3, "should have H3 headings")
	assert.True(t, hasCodeBlock, "should have code blocks")
}
