name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    # Trigger when @claude is mentioned
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    runs-on: ubuntu-latest
    permissions:
      contents: write        # For commits and branch creation
      pull-requests: write   # For PR creation
      issues: read           # For reading issue context
      id-token: write        # For OAuth authentication
      actions: read          # For CI/CD integration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}

          # Tool permissions for autonomous development
          # Using comma-separated format per official documentation
          claude_args: --allowedTools "Bash(gh pr create:*),Bash(gh pr view:*),Bash(gh pr list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr review:*),Bash(gh issue view:*),Bash(gh issue list:*),Bash(gh issue comment:*),Bash(gh api:*),Bash(gh search:*),Bash(gh label:*),Bash(gh release:*),Bash(git:*),Bash(make:*),Bash(go:*),Bash(npm:*),Bash(npx:*),Bash(pnpm:*),Bash(node:*),Bash(sed:*),Bash(awk:*),Bash(wc:*),Bash(sort:*),Bash(cut:*),Bash(ls:*),Bash(mkdir:*),Bash(mv:*),Bash(cp:*),Bash(rm:*),Bash(curl:*),Bash(jq:*),Bash(tar:*),Bash(zip:*),Bash(unzip:*),Edit,Read,Write,Glob,Grep"

          # GitHub Actions permissions (not tool permissions)
          additional_permissions: |
            actions: read

          # No prompt specified - uses Interactive Mode
          # In Interactive Mode, Claude automatically:
          # - Reads CLAUDE.md and CONTRIBUTING.md for project patterns
          # - Reads issue descriptions and acceptance criteria
          # - Checks issue dependencies naturally
          # - Follows quality gates (make lint, make test from CLAUDE.md)
          # - Creates branches with proper naming
          # - Creates PRs with proper references (Closes #N)
          # - Provides progress updates via tracking comments
